# .circleci/config.yml

# Specify the config version - version 2.1 is latest.
version: 2.1
# Specify Terraform version
orbs:
  terraform: circleci/terraform@3.1.0

# Note: These are provided by the ap-fsharp-template-resource-credentials-labs context
# - AZ_SERVICE_PRINCIPAL_APP_ID
# - AZ_SERVICE_PRINCIPAL_APP_PASSWORD

# Note: These are provided by the ap-fsharp-template-resource-credentials-preview context
# - AZ_SERVICE_PRINCIPAL_APP_ID
# - AZ_SERVICE_PRINCIPAL_APP_PASSWORD

# Note: These are provided by the ap-fsharp-template-resource-credentials-cloud context
# - AZ_SERVICE_PRINCIPAL_APP_ID
# - AZ_SERVICE_PRINCIPAL_APP_PASSWORD

# Note: These are provided by the az-resources context
# - AZ_TENANT
# - AZ_SUBSCRIPTION_ID

# Define the jobs for the current project.
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
      - checkout
      - run:
          name: Build
          command: dotnet build
          working_directory: FSharpTemplate
#  azure_login:
#    docker:
#      - image: mcr.microsoft.com/azure-cli:latest
#        user: root
#    steps:
#      - checkout
#      - run:
#          name: Login
#          command: az login --service-principal -u $AZ_SERVICE_PRINCIPAL_APP_ID -p $AZ_SERVICE_PRINCIPAL_APP_PASSWORD --tenant $AZ_TENANT
#      - run:
#          name: Set Subscription Id
#          command: az account set -s $AZ_SUBSCRIPTION_ID
  terraform-single-job:
    executor: terraform/default
    steps:
      - checkout
      - terraform/init:
          path: .
      - terraform/validate:
          path: .
      - terraform/fmt:
          path: .
      - terraform/plan:
          parameters:
            azure_subscription_id:
              default: $AZ_SUBSCRIPTION_ID
              description: Azure Subscription Id
              type: string
            azure_subscription_tenant_id:
              default: $AZ_TENANT
              description: Azure Tenant Id
              type: string
            service_principal_appid:
              default: $AZ_SERVICE_PRINCIPAL_APP_ID
              description: Azure Service Principal App Id
              type: string
            service_principal_password:
              default: $AZ_SERVICE_PRINCIPAL_APP_PASSWORD
              description: Azure Service Principal Password
              type: string
          path: .
      - terraform/apply:
          parameters:
            azure_subscription_id:
              default: $AZ_SUBSCRIPTION_ID
              description: Azure Subscription Id
              type: string
            azure_subscription_tenant_id:
              default: $AZ_TENANT
              description: Azure Tenant Id
              type: string
            service_principal_appid:
              default: $AZ_SERVICE_PRINCIPAL_APP_ID
              description: Azure Service Principal App Id
              type: string
            service_principal_password:
              default: $AZ_SERVICE_PRINCIPAL_APP_PASSWORD
              description: Azure Service Principal Password
              type: string
          path: .
    working_directory: ~/FSharpTemplate/Terraform

workflows:
  deploy_infrastructure:
    jobs:
      - build
#      - azure_login:
#          requires:
#            - build
      - terraform-single-job:
          requires:
#            - azure_login
            - build 